version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
    labels:
      - "dependencies"
    target-branch: "dependabot-weekly-update"
