version: '3'
services:
  web:
    environment:
      DB_HOST: mysql
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
    - .:/app
    # - logvolume01:/var/log
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7.33
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
# volumes:
#   logvolume01: {}
