version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers-legacy
        environment:
          RAILS_ENV: test
    executor: ruby/default
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  run_rspec:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers-legacy
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7.20
    executor: ruby/default
    working_directory: ~/project
    steps:
      - ruby/rspec-test
      - run: bundle exec rspec
