version: 2.1

executors:
  default_executor:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers-legacy
        environment:
          RAILS_ENV: test
          BUNDLE_PATH: vendor/bundle
      - image: circleci/mysql:5.7

jobs:
  build:
    executor: default_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run: bundle clean
      - save_cache:
          key:
            v1-bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # https://circleci.com/docs/ja/2.0/configuration-reference/#persist_to_workspace
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  run_rubocop:
    executor: default_executor
    steps:
      - attach_workspace:
          at: ~/project
      - run: mkdir /tmp/test-results
      - run: cd ~/project
      - run: bundle exec rubocop --format junit --out /tmp/test-results/rubocop.xml
      - store_test_results:
          path: /tmp/test-results

  run_rspec:
    executor: default_executor
    steps:
      - attach_workspace:
          at: ~/project
      - run: mkdir /tmp/test-results
      - run: cd ~/project
      - run: ./bin/rake db:create
      - run: bundle exec ridgepole -c config/database.yml -f Schemafile --apply --env test
      - run: bundle exec rspec --out /tmp/test-results/rspec.xml
      # - store_test_results:
      #     path: /tmp/test-results
      # - store_artifacts:
      #     path: /tmp/test-results

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - run_rubocop:
          requires:
            - build
      # - run_rspec:
      #     requires:
      #       - build
